In [81]:
from torchvision.datasets import CIFAR10, CIFAR100, MNIST, KMNIST, FashionMNIST
import numpy as np
from torchvision import transforms
import matplotlib.pyplot as plt

In [40]:
d = KMNIST(root="/data/datasets/kmnist", train=True).data
d = d / 255.
d.shape, d.mean(), d.std()

(torch.Size([60000, 28, 28]), tensor(0.1918), tensor(0.3483))

In [41]:
d = MNIST(root="/data/datasets/mnist", train=True).data
d = d / 255.
d.shape, d.mean(), d.std()

(torch.Size([60000, 28, 28]), tensor(0.1307), tensor(0.3081))

In [79]:
d = FashionMNIST(root="/data/datasets/fashionmnist", train=True).data
d = d / 255.
d.shape, d.mean(), d.std()

(torch.Size([60000, 28, 28]), tensor(0.2860), tensor(0.3530))

In [77]:
d = CIFAR10(root="/data/datasets/cifar10", train=True).data
d = d.reshape(-1, 3) / 255.
d.shape, d.mean(axis=0), d.std(axis=0)

((51200000, 3),
 array([0.49139968, 0.48215841, 0.44653091]),
 array([0.24703223, 0.24348513, 0.26158784]))

In [78]:
d = CIFAR100(root="/data/datasets/cifar100", train=True).data
d = d.reshape(-1, 3) / 255.
d.shape, d.mean(axis=0), d.std(axis=0)

((51200000, 3),
 array([0.50707516, 0.48654887, 0.44091784]),
 array([0.26733429, 0.25643846, 0.27615047]))